### ISSUE TITLE
Enforcing warning messages

### ISSUE THREAD

**Issue by prkriley** [jkjk822/tests#26]
https://github.com/jkjk822/tests/blob/17db52be5b3cfaf2ebecd0bfb13dfd322bfacde3/tests/scohen32_enum_spec.rb#L138

I don't recall any indication in class or in the assignment that we need to match warning output; doesn't seem reasonable to deduct points for it.

**Comment by jkjk822** [comment]
Chen said it was extra credit in class I believe. But yes, I will remove this test.
