### ISSUE TITLE
Wrong Minitest Class

### ISSUE THREAD

**Issue by prkriley** [jkjk822/tests#7]
https://github.com/jkjk822/tests/blob/30fa2b8994b41f499d49cfdcce3d21314a20b501/tests/hjohnsto_enum_tests.rb#L4

This kills my run; Minitest says it should be Minitest::Test

**Comment by jkjk822** [comment]
What version of Ruby are you using? 2.4.1 gives this:  (but only as a warning, still runs fine)

> MiniTest::Unit::TestCase is now Minitest::Test.
From GitHub/tests/tests/hjohnsto_enum_tests.rb:4:in `<top (required)>'

I'll go ahead and change it since I'm editing other things.
