### ISSUE TITLE
Assuming Discouraged Behavior

### ISSUE THREAD

**Issue by prkriley** [jkjk822/tests#8]
https://github.com/jkjk822/tests/blob/30fa2b8994b41f499d49cfdcce3d21314a20b501/tests/pferner2_enum_test.rb#L128

This assumes the blockless enum-return variant that we were discouraged from implementing. It should not be tested for. There are others like it in this file.

**Comment by jkjk822** [comment]
Fixed 3 occurrences. Again let me know if other cases are there.
