### ISSUE TITLE
Assuming Discouraged Behavior

### ISSUE THREAD

**Issue by prkriley** [jkjk822/tests#9]
https://github.com/jkjk822/tests/blob/30fa2b8994b41f499d49cfdcce3d21314a20b501/tests/wcohen4_enum_tests.rb#L117

This assumes the blockless enum-return variant that we were discouraged from implementing. It should not be tested for. There are others like it in this file.

**Comment by jkjk822** [comment]
I fixed the two cases involving `each_with_index` specifically. Please let me know if there are similar cases with other methods.
